export const styles = {
  pageContainer: {
    minHeight: '100vh',
    backgroundColor: '#f9fafb',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    backgroundColor: 'white',
    boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
  },
  headerContent: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '0 1rem',
  },
  headerFlex: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '64px',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#4f46e5',
  },
  logoText: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
  },
  navButtons: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  marketplaceBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#4f46e5',
    color: 'white',
    borderRadius: '0.5rem',
    border: 'none',
    cursor: 'pointer',
    fontWeight: '500',
  },
  postBtn: {
    padding: '0.5rem 1.5rem',
    backgroundColor: '#4f46e5',
    color: 'white',
    borderRadius: '0.5rem',
    border: 'none',
    cursor: 'pointer',
    fontWeight: '500',
  },
  accountBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    backgroundColor: '#1f2937',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
  },
  dropdown: {
    position: 'absolute',
    right: 0,
    marginTop: '0.5rem',
    width: '288px',
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)',
    border: '1px solid #e5e7eb',
    padding: '0.5rem 0',
    zIndex: 50,
  },
  dropdownHeader: {
    width: '100%',
    padding: '0.5rem 1rem',
    textAlign: 'left',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
  },
  userInfo: {
    padding: '0.75rem 1rem',
    borderBottom: '1px solid #f3f4f6',
  },
  userFlex: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  avatar: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(to bottom right, #818cf8, #a78bfa)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: '600',
  },
  userName: {
    fontWeight: '500',
    color: '#111827',
  },
  userEmail: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    backgroundColor: '#22c55e',
    borderRadius: '50%',
    marginLeft: 'auto',
  },
  menuItem: {
    width: '100%',
    padding: '0.5rem 1rem',
    textAlign: 'left',
    color: '#374151',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
  },
  themeRow: {
    padding: '0.5rem 1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleBtn: (active) => ({
    width: '48px',
    height: '24px',
    borderRadius: '9999px',
    backgroundColor: active ? '#22c55e' : '#d1d5db',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
  }),
  toggleCircle: (active) => ({
    width: '20px',
    height: '20px',
    backgroundColor: 'white',
    borderRadius: '50%',
    boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
    transform: active ? 'translateX(24px)' : 'translateX(4px)',
    transition: 'transform 0.2s',
    position: 'absolute',
    top: '2px',
  }),
  hero: {
    background: 'linear-gradient(to right, #4f46e5, #4338ca)',
    color: 'white',
    padding: '4rem 0',
  },
  heroContent: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '0 1rem',
    textAlign: 'center',
  },
  heroTitle: {
    fontSize: '3rem',
    fontWeight: 'bold',
    marginBottom: '1rem',
  },
  heroSubtitle: {
    fontSize: '1.25rem',
    color: '#c7d2fe',
    marginBottom: '2rem',
  },
  searchBar: {
    maxWidth: '768px',
    margin: '0 auto',
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
    display: 'flex',
    alignItems: 'center',
    overflow: 'hidden',
  },
  searchInputWrapper: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    padding: '0 1rem',
  },
  searchInput: {
    flex: 1,
    padding: '1rem',
    border: 'none',
    outline: 'none',
    color: '#374151',
  },
  categorySelect: {
    padding: '1rem 1.5rem',
    borderLeft: '1px solid #e5e7eb',
    border: 'none',
    outline: 'none',
    color: '#374151',
    backgroundColor: 'white',
    cursor: 'pointer',
  },
  main: {
    flex: 1,
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '3rem 1rem',
    width: '100%',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '2rem',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  title: {
    fontSize: '1.875rem',
    fontWeight: 'bold',
    color: '#111827',
  },
  filterButtons: {
    display: 'flex',
    gap: '0.5rem',
  },
  filterBtn: (active) => ({
    padding: '0.5rem 1rem',
    borderRadius: '0.5rem',
    fontWeight: '500',
    border: 'none',
    cursor: 'pointer',
    backgroundColor: active ? '#4f46e5' : 'white',
    color: active ? 'white' : '#374151',
  }),
  itemsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '1.5rem',
  },
  itemCard: {
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
    overflow: 'hidden',
    cursor: 'pointer',
  },
  itemImage: {
    width: '100%',
    aspectRatio: '1',
    backgroundColor: '#e5e7eb',
  },
  itemContent: {
    padding: '1rem',
  },
  itemTitle: {
    fontWeight: '600',
    color: '#111827',
    marginBottom: '0.25rem',
  },
  itemPrice: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: '0.5rem',
  },
  itemDescription: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  footer: {
    backgroundColor: '#1f2937',
    color: '#d1d5db',
    padding: '2rem 0',
    marginTop: '3rem',
  },
  footerContent: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '0 1rem',
    textAlign: 'center',
  },
  footerText: {
    marginBottom: '0.5rem',
  },
  contactBtn: {
    color: '#818cf8',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
  },
};
